POST http://localhost:3003/user/register
Content-Type: application/json

{
    "nome": "João",
    "nascimento": "01011990",
    "salario": "3000",
    "departamento": "administrativo"
}

#######
GET http://localhost:3003/user/getUsers
Content-Type: application/json


#######
GET http://localhost:3003/user/getUserById/1
Content-Type: application/json

######

PUT http://localhost:3003/user/updateUser/3
Content-Type: application/json

{
    "nome": "João",
    "nascimento": "01011990",
    "salario": "3000",
    "departamento": "sup"s
}

######

DELETE http://localhost:3003/user/deleteUser/1
Content-Type: application/json

